name: Maybe Finance
description: >-
  Maybe Finance is a personal finance management application that helps you
  track your expenses, income, and investments.
slug: maybe_finance
init: false
arch:
  - armhf
  - aarch64
  - amd64
#  - armv7
#  - i386
startup: application
boot: auto
#ingress: true
#ingress_port: 3000
webui: "[PROTO:rails_force_ssl]://[HOST]:[PORT:3000]"
url: https://github.com/M123-dev/maybe_finance_hass
ports:
  3000/tcp: 1234
map:
  - "data:rw"
schema:
  postgres_password: str
  secret_key_base: str
  db_host: str?
  db_port: str?
  postgres_user: str?
  #app_domain: str
  plaid_client_id: str?
  plaid_secret: str?
  plaid_env: str?
  self_hosted: bool
  rails_force_ssl: bool
  rails_assume_ssl: bool
  good_job_execution_mode: str
  require_invite_code: bool
options:
  postgres_password: "homeassistant"
  secret_key_base: "generate_a_secure_key_here"
  db_host: "172.30.32.1"
  db_port: "5432"
  postgres_user: "postgres"
  #  app_domain: "http://localhost"
  self_hosted: true
  rails_force_ssl: false
  rails_assume_ssl: false
  good_job_execution_mode: "async"
  require_invite_code: true
version: 0.4.7
#build:
#  dockerfile: Dockerfile
#  args:
#    BUILD_ARCH: "{arch}"
image: ghcr.io/m123-dev/{arch}-maybe_finance_homeassistant
#build_from:
#  armv7: "ghcr.io/home-assistant/armv7-base:latest"
#  amd64: "ghcr.io/home-assistant/amd64-base:latest"
#  armhf: "ghcr.io/home-assistant/armhf-base:latest"
#  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
#  i386: "ghcr.io/home-assistant/i386-base:latest"


